#!/bin/sh

# @usage
# This script is used for testing purposes, github raw files are cached and might take to update any changes made to this file, renaming might help for faster debugging.
#
# With params
# curl -sfL https://raw.githubusercontent.com/k-marin/scripts/main/remote-echo | sh -s param1 param2
#
# Without params
# curl -sfL https://raw.githubusercontent.com/k-marin/scripts/main/remote-echo | sh -

echo "Remote script executed param1=$1 param2=$2."