#!/bin/sh

# @usage 
# With params
# curl -sfL https://raw.githubusercontent.com/k-marin/scripts/main/remote-echo | sh -s param1 param2
#
# Without params
# curl -sfL https://raw.githubusercontent.com/k-marin/scripts/main/remote-echo | sh -

echo "Remote script executed param1=$1 param2=$2."