#!/bin/sh

# Without params and with cache bust - Github raw files Cache-Control: max-age=300 in order to avoid caching use the command below for testing.
# curl -sfL -H 'Cache-Control: no-cache, no-store' https://raw.githubusercontent.com/k-marin/scripts/main/simple-server | sh -s yourdomain.com 8080

# error handling
set -e

DOMAIN_NAME="yourdomain.com"
PORT_NO=8080
# if [ ! -z "$1" -a "$!" != " " ]; then
#     DOMAIN_NAME=$1
# fi
# if [ ! -z "$2" -a "$!" != " " ]; then
#     PORT_NO=$2
# fi

read -d '' INDEX << EOF
<html>
 <head>
  <title>Welcome to the $DOMAIN_NAME</title>
 <head>
 <body>Latest news about $DOMAIN_NAME</body>
</html>
EOF
while true;
do
    (echo -e "HTTP/1.1 200 OK\r\nContent-Length: $(expr length "$INDEX")\r\n"; echo $INDEX; ) | nc -l $PORT_NO;
done